### ISSUE TITLE
ArgumentOutOfRangeException: Argument is out of range. Parameter name: index

### ISSUE THREAD

**Issue by DiSaber** [alwyntan/Crossy-Road-AI#2]
When I first opened and ran the scene alwyn scene unity throws me this error: FileNotFoundException: Could not find file "C:\Users\marc\Downloads\Crossy-Road-AI-master\Crossy-Road-AI-master\Assets\Resources\weight.txt".
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:305)
System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share)
(wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.OpenRead (System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:363)
System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamReader.cs:167)
System.IO.StreamReader..ctor (System.String path)
(wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (string)
GameTreeAI.readWeight () (at Assets/Scripts/GameTreeAI.cs:44)
GameTreeAI..ctor (.GameState gameState, Int32 depthSetting, Single AIMoveInterval) (at Assets/Scripts/GameTreeAI.cs:186)
AIScript.Start () (at Assets/Scripts/AIScript.cs:31)

I created the weight.txt file and added the number 1 to the contents of the file. Unity now throws me this error:
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[System.Single].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
GameTreeAI.linearCombination (System.Collections.Generic.List`1 weight, System.Collections.Generic.List`1 state) (at Assets/Scripts/GameTreeAI.cs:123)
GameTreeAI.FindVOpt (System.Collections.Generic.List`1 currstate, System.Collections.Generic.List`1 weight) (at Assets/Scripts/GameTreeAI.cs:85)
GameTreeAI.FindBestMove () (at Assets/Scripts/GameTreeAI.cs:195)
AIScript.Update () (at Assets/Scripts/AIScript.cs:64)

I tried other numbers like -1, -5, 0, 2, 5, 25...etc
I also removed the // on line 124 of the GameTreeAI.cs script and the log shows this:
One line 1 0 their value 0
UnityEngine.Debug:Log(Object)
GameTreeAI:linearCombination(List`1, List`1) (at Assets/Scripts/GameTreeAI.cs:124)
GameTreeAI:FindVOpt(List`1, List`1) (at Assets/Scripts/GameTreeAI.cs:85)
GameTreeAI:FindBestMove() (at Assets/Scripts/GameTreeAI.cs:195)
AIScript:Update() (at Assets/Scripts/AIScript.cs:64)
![Unity 2018 2 14f1 Personal (64bit) - alwyn scene unity - Crossy-Road-AI-master - PC, Mac   Linux Standalone _DX11_ 5_5_2019 8_20_38 AM](https://user-images.githubusercontent.com/37475791/57194638-ba758500-6f0e-11e9-9759-9aaf07672f4e.png)

**Comment by alwyntan** [comment]
@SajanaW Could you taking a look at this and see how you created the weights back then?

**Comment by alwyntan** [comment]
It's fixed
